name: mafioso_game
description: Mafioso game
publish_to: "none"
version: 1.0.1

environment:
  sdk: ">=3.3.0 <3.6.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: 2.5.3
  supabase_flutter: 2.6.0
  package_info_plus: 8.3.1
  url_launcher: 6.3.1

dependency_overrides:
  app_links: 6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.2
  flutter_launcher_icons: 0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/logo/
    - assets/photos/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajawal-Black.ttf

flutter_launcher_icons:
  android: true
  ios: true

  # Android 12+ Adaptive Icon (حل مشكلة ظهور الروبوت الافتراضي)
  adaptive_icon_foreground: "assets/logo/logo.png"
  adaptive_icon_background: "#000000"

  # للأجهزة الأقدم أيضًا
  image_path: "assets/logo/logo.png"
